### ISSUE TITLE
Date selector funktioniert nicht

### ISSUE THREAD

**Issue by dem2k** [dem2k/Zeiterfassung#2]
1. Man kann den 30. Februar auswählen
2. Der Monat im  Datum wird einstellig formatiert. z.B. 2020-2-15. Dieses Format kann nicht geparst werden:
`2020-10-21 17:09:01.715  WARN 15024 --- [nio-8080-exec-4] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Cannot deserialize value of type java.time.LocalDate from String "2020-2-15": Failed to deserialize java.time.LocalDate: (java.time.format.DateTimeParseException) Text '2020-2-15' could not be parsed at index 5; nested exception is com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type java.time.LocalDate from String "2020-2-15": Failed to deserialize java.time.LocalDate: (java.time.format.DateTimeParseException) Text '2020-2-15' could not be parsed at index 5`

**Comment by alexkleyn** [comment]
Format des Datums und Anzahl der auswählbaren Tage gefixed.
